# Generated by Django 3.2.6 on 2021-09-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0002_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='OTP',
            new_name='user_otp',
        ),
    ]
