# Generated by Django 3.2.6 on 2021-09-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0004_otp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='Name',
            new_name='reg_name',
        ),
    ]
