# Generated by Django 3.2.6 on 2021-09-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0005_rename_name_otp_reg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='reg_name',
            new_name='Name',
        ),
    ]
