# Generated by Django 3.2.6 on 2021-09-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0010_auto_20210919_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.AddField(
            model_name='register',
            name='Gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
