# Generated by Django 3.2.6 on 2021-09-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0011_auto_20210919_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Number',
            new_name='Passcode',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='Username',
        ),
    ]
