# Generated by Django 3.2.6 on 2021-09-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0012_auto_20210919_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Number',
            field=models.IntegerField(null=True),
        ),
    ]
