# Generated by Django 3.2.6 on 2021-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0014_otp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Singer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
